---
title: "simulating RSA results"
output: html_document
---

```{r setup, include = FALSE}

library(here)
library(dplyr)
library(tidyr)
library(ggplot2)
library(data.table)
library(knitr)
library(ggridges)
library(foreach)
library(doParallel)
library(httpgd)
source(here::here("src", "stroop-rsa-pc.R"))

opts_chunk$set(echo = TRUE)
theme_set(theme_bw(base_size = 14))
hgd()

```


## parameters

simulate beta coefficient estimates directly

```{r}

ttypes <- sort(ttypes)
target <- gsub("[A-Z]", "", ttypes)
distractor <- gsub("[a-z]", "", ttypes)
incongruency <- as.character(target != tolower(distractor))
conjunction <- paste0(target, distractor)

R_target <- tcrossprod(indicator_matrix(target))
R_distractor <- tcrossprod(indicator_matrix(distractor))
R_incongruency <- tcrossprod(cbind(indicator_matrix(incongruency)[, "TRUE"]))
R_conjunction <- tcrossprod(indicator_matrix(conjunction))

ttype_subset <- "pc50"
session <- "reactive"
meancenter <- FALSE
p <- 100  ## number vertex
snr <- 0.1
true_weights <- c(1, 1, 1, 1) ## distractor, conjunction, incongruency, target
S <- 
    true_weights[1]*R_distractor + 
    true_weights[2]*R_conjunction + 
    true_weights[3]*R_incongruency + 
    true_weights[4]*R_target

X_dist <- cbind(
    intercept = 1,
    distractor = vec(read_model_rdm(model = "distractor", "cvdistance", session, ttype_subset)), 
    incongruency = vec(read_model_rdm(model = "incongruency", "cvdistance", session, ttype_subset)),
    target = vec(read_model_rdm(model = "target", "cvdistance", session, ttype_subset))
    )
X_simil <- cbind(
    intercept = 1,
    distractor = c(read_model_rdm(model = "distractor", "similarity", session, ttype_subset)), 
    conjunction = c(read_model_rdm(model = "conjunction", "similarity", session, ttype_subset)),
    incongruency = c(read_model_rdm(model = "incongruency", "similarity", session, ttype_subset)),
    target = c(read_model_rdm(model = "target", "similarity", session, ttype_subset))
    )

n_sims <- 1E3
cl <- makeCluster(20, type = "FORK")
registerDoParallel(cl)
res <- foreach(sim_i = seq_len(n_sims), .combine = rbind) %dopar% {
    #sim_i = 1
    set.seed(sim_i)

    B <- MASS::mvrnorm(n = p, mu = rep(0, nrow(S)), Sigma = S)
    colnames(B) <- ttypes
    if (meancenter) {
        B <- t(scale(t(B)))  ## row mean center
        #m <- scale2unit(rowMeans(B))  ## pattern center
        #B <- B - m %*% crossprod(m, B)
    }

    ttypes_run1 <- rownames(read_model_rdm(model = "distractor", "cvdistance", session, ttype_subset))
    ttypes_run2 <- colnames(read_model_rdm(model = "distractor", "cvdistance", session, ttype_subset))
    B1 <- B[, ttypes_run1]
    B2 <- B[, ttypes_run2]

    B1_hat <- B1 + rnorm(p*ncol(B1), sd = 1/snr)
    B2_hat <- B2 + rnorm(p*ncol(B2), sd = 1/snr)

    D <- cvdist(B1_hat, B2_hat)
    R <- cor(B1_hat, B2_hat)

    b_simil <- coef(.lm.fit(x = X_simil, y = atanh(c(R))))
    b_dist <- coef(.lm.fit(x = X_dist, y = vec(D)))
    
    b_simil <- data.table(
        b = b_simil, 
        term = c("intercept", "distractor", "conjunction", "incongruency", "target"),
        measure = "simil",
        simulation = sim_i
        )

    b_dist <- data.table(
        b = b_dist, 
        term = c("intercept", "distractor", "incongruency", "target"),
        measure = "dist",
        simulation = sim_i
    )

    rbind(b_simil, b_dist)

}
stopImplicitCluster()

res %>%
    mutate(experiment = ntile(simulation, n_sims/25)) %>%
    group_by(experiment, measure, term) %>%
    summarize(stat = t.test(b, alternative = "greater")$statistic) %>%
    group_by(term, measure) %>%
    summarize(stat = mean(stat))

```
